log:
  log_dir: "outputs/logs"
  console_level: "INFO"
  file_level: "DEBUG"
  rotation: "200 MB"
  retention: "14 days"

llm:
  openai:
    gpt-4o-mini:
      timeout: 60
    gpt-4o:
      timeout: 60
  deepseek:
    deepseek-chat:
      timeout: 30
      endpoint: https://api.deepseek.com
    deepseek-reasoner:
      timeout: 30
      endpoint: https://api.deepseek.com

templates:
  prompts: "templates/prompts"
  queries: "templates/queries"

seq2seq:
  max_length: 512

  inference:
    batch_size: 32

  training:
    batch_size: 64
    learning_rate: 3e-5
    num_epochs: 100
    early_stopping: 15
    warmup_proportion: 0.1
    gradient_accumulation_steps: 1
    max_grad_norm: 1.0
    weight_decay: 1e-5

  checkpoints:
    kqapro_ir:
      path: "models/checkpoints/kqapro_ir/checkpoint-best"
      dataset: "kqapro"
      lang: "sparql"
      ir_mode: "graphq"
    metaqa_ir:
      path: "models/checkpoints/metaqa_ir/5shot/checkpoint-best"
      dataset: "metaqa"
      lang: "cypher"
      ir_mode: "graphq"
    metaqa_ir_T_kqapro_ir:
      path: "models/checkpoints/metaqa_ir_T_kqapro_ir/checkpoint-best"
      dataset: "metaqa"
      lang: "cypher"
      ir_mode: "graphq"
      transfer_from: "kqapro_ir"

data:
  base_dir: "data"

  kqapro:
    src: "data/kqapro/src.db"
    dst: "data/kqapro/dst.db"
    train:
      raw: "data/kqapro/train/raw"
      processed: "data/kqapro/train/processed"
      config_sparql: "data/kqapro/train/raw/config_sparql.py"
      config_kopl: "data/kqapro/train/raw/config_kopl.py"
    eval:
      raw: "data/kqapro/eval/raw"
      processed: "data/kqapro/eval/processed"

  metaqa:
    src: "data/metaqa/storage/src.db"
    dst: "data/metaqa/storage/dst.db"
    train:
      raw: "data/metaqa/train/raw"
      processed: "data/metaqa/train/processed"
      config: "data/metaqa/train/raw/config.py"
      shots:
        1shot: "data/metaqa/train/processed/1shot"
        3shot: "data/metaqa/train/processed/3shot"
        5shot: "data/metaqa/train/processed/5shot"
    eval:
      data: "data/metaqa/eval/processed/data.json"
      group_by:
        - hop
        - split
    schema:
      cypher: "data/metaqa/schema/cypher.json"
      sparql: "data/metaqa/schema/sparql.json"
      gremlin: "data/metaqa/schema/gremlin.json"
    connection:
      cypher:
        host: localhost
        port: 7601
        username: neo4j
        password: MetaQANeo4j
        database: neo4j
        sanity:
          - lowercase_relationships
      sparql:
        data_path: "data/metaqa/server/sparql/metaqa.ttl"
        data_format: "turtle"
      gremlin:
        host: localhost
        port: 8182
        docker_compose: "data/metaqa/server/gremlin/docker-compose.yml"

  openreview:
    src: "data/openreview/storage/src.db"
    dst: "data/openreview/storage/dst.db"
    train:
      raw: "data/openreview/train/raw"
      processed: "data/openreview/train/processed"
      config: "data/openreview/train/raw/config.py"
    eval:
      raw: "data/openreview/eval/raw"
      processed: "data/openreview/eval/processed"
    schema:
      cypher: "data/openreview/schema/cypher.json"
      sparql: "data/openreview/schema/sparql.json"
      gremlin: "data/openreview/schema/gremlin.json"
    connection:
      cypher:
        host: localhost
        port: 7602
        username: neo4j
        password: OpenReviewNeo4j
        database: neo4j
      sparql:
        data_path: "data/openreview/server/sparql/openreview.ttl"
        data_format: "turtle"
      gremlin:
        host: localhost
        port: 8183
        docker_compose: "data/openreview/server/gremlin/docker-compose.yml"



